name: dollar_dash
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  go_router: ^14.2.3
  fluttertoast: ^8.2.6
  flutter_spinbox: ^0.13.1
  dropdown_textfield: ^1.2.0
  calendar_date_picker2: ^1.1.5
  collection: ^1.18.0
  slideable: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: SC
      fonts:
        - asset: assets/fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SourceCodePro-Black.ttf
          weight: 900